# Change these first
owner: subspace # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

assignees:
  - ImmaZoni
  - isSerge
sites:
  - name: Subspace Labs Website
    url: https://www.subspace.network
  - name: "Gemini-II EU-0 RPC endpoint"
    check: "tcp-ping"
    url: "eu-0.gemini-2a.subspace.network"
  - name: "Gemini-III EU-0 RPC endpoint"
    check: "tcp-ping"
    url: "eu-0.gemini-3c.subspace.network"
  - name: "Gemini-III EU-1 RPC endpoint"
    check: "tcp-ping"
    url: "eu-1.gemini-3c.subspace.network"
  - name: "Gemini-III EU-2 RPC endpoint"
    check: "tcp-ping"
    url: "eu-2.gemini-3c.subspace.network"
  # perform easiest queries for GraphQL endpoints
  # for more details: https://www.apollographql.com/docs/apollo-server/monitoring/health-checks/#graphql-level-health-checks
  - name: "Gemini-II block explorer squid GraphQL endpoint"
    url: "squid.gemini-2a.subspace.network/graphql?query=%7B__typename%7D"
  - name: "Gemini-III block explorer squid GraphQL endpoint"
    url: "squid.gemini-3b.subspace.network/graphql?query=%7B__typename%7D"
  - name: "Gemini-III Subsquid archive API endpoint"
    url: "archive.gemini-3c.subspace.network/api?query=%7B__typename%7D"
  - name: "Gemini-III Subsquid archive GraphQL endpoint"
    url: "archive.gemini-3b.subspace.network/graphql?query=%7B__typename%7D"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /status
  cname: status.subspace.network
  theme: light
  favicon: https://uploads-ssl.webflow.com/6108908c3729aa7f2ffe5c29/610890e755d89332b2d39351_cee1c0fb-subspace-logo_102e02c000000000000028.png
  logoUrl: https://uploads-ssl.webflow.com/6108908c3729aa7f2ffe5c29/610890e755d89332b2d39351_cee1c0fb-subspace-logo_102e02c000000000000028.png
  name: Subspace Network Status Page
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/subspace/
    - title: Website
      href: https://subspace.network/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
