# Change these first
owner: subspace # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

assignees:
  - ImmaZoni
sites:
  - name: Subspace Labs Website
    url: https://www.subspace.network
    icon: https://uploads-ssl.webflow.com/6108908c3729aa7f2ffe5c29/610890e755d89332b2d39351_cee1c0fb-subspace-logo_102e02c000000000000028.png
  - name: Spartan Testnet
    check: "tcp-ping"
    url: 165.232.157.230
    port: 30333
    icon: https://uploads-ssl.webflow.com/6108908c3729aa7f2ffe5c29/610890e755d89332b2d39351_cee1c0fb-subspace-logo_102e02c000000000000028.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.subspace.network
  theme: light
  favicon: https://uploads-ssl.webflow.com/6108908c3729aa7f2ffe5c29/610890e755d89332b2d39351_cee1c0fb-subspace-logo_102e02c000000000000028.png
  # baseUrl: /Uptime
  logoUrl: https://uploads-ssl.webflow.com/6108908c3729aa7f2ffe5c29/610890e755d89332b2d39351_cee1c0fb-subspace-logo_102e02c000000000000028.png
  name: Subspace Network Status Page
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/subspace/
    - title: Website
      href: https://subspace.network/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration


i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
